//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebBanHangEntities : DbContext
    {
        public WebBanHangEntities()
            : base("name=WebBanHangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand_2119110325> Brand_2119110325 { get; set; }
        public virtual DbSet<Category_2119110325> Category_2119110325 { get; set; }
        public virtual DbSet<Order_2119110325> Order_2119110325 { get; set; }
        public virtual DbSet<OrderDetail_2119110325> OrderDetail_2119110325 { get; set; }
        public virtual DbSet<Product_2119110325> Product_2119110325 { get; set; }
        public virtual DbSet<Users_2119110325> Users_2119110325 { get; set; }

        public System.Data.Entity.DbSet<WebBanHang.Context.ProductMasterData> ProductMasterDatas { get; set; }

        public System.Data.Entity.DbSet<WebBanHang.Context.BrandMasterData> BrandMasterDatas { get; set; }
    }
}
